/*
* SPDX-FileCopyrightText: 2024-2025 Sony Semiconductor Solutions Corporation
*
* SPDX-License-Identifier: Apache-2.0
*/
#ifndef SENSCORD_CONFIG_H_
#define SENSCORD_CONFIG_H_

#ifdef __NuttX__
#include <nuttx/config.h>
#endif  /* __NuttX__ */

#ifdef CONFIG_EXTERNAL_SENSCORD_LIGHTWEIGHT
#define SENSCORD_LIGHTWEIGHT
#endif  /* CONFIG_EXTERNAL_SENSCORD_LIGHTWEIGHT */

#ifdef CONFIG_SENSCORD_CONFIG_SHARING
#define SENSCORD_CONFIG_SHARING
#endif  /* CONFIG_SENSCORD_CONFIG_SHARING */

#ifdef CONFIG_EXTERNAL_SENSCORD_API_C
#define SENSCORD_API_C
#endif  /* CONFIG_EXTERNAL_SENSCORD_API_C */

#ifdef CONFIG_EXTERNAL_SENSCORD_API_WASM
#define SENSCORD_API_WASM
#endif  /* CONFIG_EXTERNAL_SENSCORD_API_WASM */

#ifdef CONFIG_EXTERNAL_SENSCORD_STREAM_EVENT_ARGUMENT
#define SENSCORD_STREAM_EVENT_ARGUMENT
#endif  /* CONFIG_EXTERNAL_SENSCORD_STREAM_EVENT_ARGUMENT */

#ifdef CONFIG_EXTERNAL_SENSCORD_STREAM_LOCK_PROPERTY
#define SENSCORD_STREAM_LOCK_PROPERTY
#endif  /* CONFIG_EXTERNAL_SENSCORD_STREAM_LOCK_PROPERTY */

#ifdef CONFIG_EXTERNAL_SENSCORD_STATUS_ON
#define SENSCORD_STATUS_MESSAGE_ENABLED
#endif  /* CONFIG_EXTERNAL_SENSCORD_STATUS_ON */

#ifdef CONFIG_EXTERNAL_SENSCORD_STATUS_DEBUG
#define SENSCORD_STATUS_DEBUG
#endif  /* CONFIG_EXTERNAL_SENSCORD_STATUS_DEBUG */

#ifdef CONFIG_SENSCORD_LOG_OFF
#define SENSCORD_LOG_OFF
#endif  /* CONFIG_SENSCORD_LOG_OFF */

#ifdef CONFIG_SENSCORD_LOG_ERROR_OUTPUT
#define SENSCORD_LOG_ERROR_OUTPUT
#endif  /* CONFIG_SENSCORD_LOG_ERROR_OUTPUT */

#ifdef CONFIG_SENSCORD_LOG_WARNING_OUTPUT
#define SENSCORD_LOG_ERROR_OUTPUT
#define SENSCORD_LOG_WARNING_OUTPUT
#endif  /* CONFIG_SENSCORD_LOG_WARNING_OUTPUT */

#ifdef CONFIG_SENSCORD_LOG_INFO_OUTPUT
#define SENSCORD_LOG_ERROR_OUTPUT
#define SENSCORD_LOG_WARNING_OUTPUT
#define SENSCORD_LOG_INFO_OUTPUT
#endif  /* CONFIG_SENSCORD_LOG_INFO_OUTPUT */

#ifdef CONFIG_SENSCORD_LOG_DEBUG_OUTPUT
#define SENSCORD_LOG_ERROR_OUTPUT
#define SENSCORD_LOG_WARNING_OUTPUT
#define SENSCORD_LOG_INFO_OUTPUT
#define SENSCORD_LOG_DEBUG_OUTPUT
#endif  /* CONFIG_SENSCORD_LOG_DEBUG_OUTPUT */

#ifdef CONFIG_SENSCORD_RAWDATA_TYPE_LENGTH
#define SENSCORD_RAWDATA_TYPE_LENGTH CONFIG_SENSCORD_RAWDATA_TYPE_LENGTH
#endif  /* CONFIG_SENSCORD_RAWDATA_TYPE_LENGTH */

#ifdef CONFIG_SENSCORD_CHANNEL_LIST_MAX
#define SENSCORD_CHANNEL_LIST_MAX CONFIG_SENSCORD_CHANNEL_LIST_MAX
#endif  /* CONFIG_SENSCORD_CHANNEL_LIST_MAX */

#ifdef CONFIG_SENSCORD_TEMPERATURE_LIST_MAX
#define SENSCORD_TEMPERATURE_LIST_MAX CONFIG_SENSCORD_TEMPERATURE_LIST_MAX
#endif  /* CONFIG_SENSCORD_TEMPERATURE_LIST_MAX */

#ifdef CONFIG_SENSCORD_CHANNEL_DESCRIPTION_LENGTH
#define SENSCORD_CHANNEL_DESCRIPTION_LENGTH CONFIG_SENSCORD_CHANNEL_DESCRIPTION_LENGTH
#endif  /* CONFIG_SENSCORD_CHANNEL_DESCRIPTION_LENGTH */

#ifdef CONFIG_SENSCORD_TEMPERATURE_DESCRIPTION_LENGTH
#define SENSCORD_TEMPERATURE_DESCRIPTION_LENGTH CONFIG_SENSCORD_TEMPERATURE_DESCRIPTION_LENGTH
#endif  /* CONFIG_SENSCORD_TEMPERATURE_DESCRIPTION_LENGTH */

#endif  /* SENSCORD_CONFIG_H_ */
